name: Deploy
on:
  workflow_run:
    workflows: ['Build']
    branches: [master]
    types:
      - completed
jobs:
  deploy:
    # only run if the build job was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            docker ps -q --filter "name=ocean-backend" | grep -q . && docker stop ocean-backend && docker rm -fv ocean-backend
            docker image prune -f
            docker pull cyberproton/ocean-backend:latest
            docker run --name ocean-backend --env-file=.env -p 3000:3000 -tid cyberproton/ocean-backend
