name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            docker ps -q --filter "name=ocean-backend" | grep -q . && docker stop ocean-backend && docker rm -fv ocean-backend
            docker pull cyberproton/ocean-backend:latest
            docker run --name ocean-backend --env-file=.env -p 3000:3000 -tid cyberproton/ocean-backend
